spring:
  application:
    name: 331-backend
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3306/selabdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB

supabase:
  storage:
    endpoint: https://unawwgkrujloenbnnmgn.storage.supabase.co/storage/v1/s3
    endpoint_output: https://unawwgkrujloenbnnmgn.storage.supabase.co/storage/v1/object/public
    bucket: imageupload
    region: ap-southeast-1
    accessKey: 80f14fbefd2b73886dbed33e9568d07b
    secretKey: 9e6d554f2cf9e84c7b65d1f0352cce6f9c40f042041c4d522200049f3ca98d72

application:
  security:
    jwt:
      secret-key: 230ef4f71d53cccce8442ab9e3de9958957c3cd210050b33848a026403cd2d3d
      expiration: 86400000 
      refresh-token:
        expiration: 604800000 # 7 days